### PR TITLE
Fix typo OTP_REQURIED

### PR DESCRIPTION
**Pull request by michalhosna**
Probably BREAKING CHANGE

Fixes contember/contember#117

### CODE REVIEW

**Comment by matej21** [comment]
Thanks. Do you have any idea why GH Actions build was not triggered?

**Comment by Cactucs** [comment]
```
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
```

This push occurred in different repository.

**Comment by matej21** [comment]
I see.. fixed in master 
@michalhosna could you please rebase this?

**Comment by michalhosna** [comment]
Done

**Pull request merged**
